[general]
import = ["~/.config/alacritty/dracula.toml"]

[window]
dimensions = { columns = 80, lines = 20 }
opacity = 0.9
blur = true

[font]
normal = { family = "HackGen Console NF", style = "Regular" }
size = 14.0
