# ~/.zshrc

# Enable zsh completion
autoload -U compinit
compinit


# Enable interactive comments
setopt interactivecomments


# Custom history
# sync history immediately between all session
setopt share_history
# don't put duplicate lines in the history
setopt hist_ignore_dups
# remove superfluous blank from each command line
setopt hist_reduce_blanks
# append to the history file, don't overwrite it
setopt inc_append_history
# set history length
HISTSIZE=100000
SAVEHIST=100000


# zsh-syntax-highlighting
if [ "$(uname)" = 'Darwin' ] && [ -f "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
    source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
elif [ "$(expr substr "$(uname -s)" 1 5)" = 'Linux' ] && [ -f '/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' ]; then
    source '/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
fi

# Enable color support of ls and also add handy aliases
# shellcheck disable=SC2003
if [ "$(uname)" = 'Darwin' ]; then
    alias ls='ls -G'
    alias grep='grep --color=auto'
elif [ "$(expr substr "$(uname -s)" 1 5)" = 'Linux' ]; then
    alias ls='ls --group-directories-first --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
fi
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Key bindings
