# ~/.bash_profile

# Change locale depending on environment
case $TERM in
    linux) export LANG=C ;;
    *)     export LANG=ja_JP.UTF-8 ;;
esac

# Enable sbin
if [ -d /usr/local/sbin ]; then
    export PATH="/usr/local/sbin:$PATH"
fi

# Enable local bin
if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# Set XDG_CONFIG_HOME
if [ "${XDG_CONFIG_HOME:+foo}" ] && [ -d "$HOME/.config" ]; then
    export XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
