name: lint

on:
  pull_request:
    branches: [ master ]
    paths:
      - install.sh
      - .github/workflows/lint.yml
  push:
    branches: [ master ]
    paths:
      - .github/workflows/lint.yml
      - install.sh
      - sh/**
      - bash/**
      - zsh/**
  workflow_dispatch:

jobs:
  lint_install_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check install.sh
        run: shellcheck install.sh
  list_shellfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shellfiles:
          - sh/profile
          - bash/bashrc
          - bash/bash_logout
          - zsh/zshrc
    steps:
      - uses: actions/checkout@v6
      - name: shellcheck ${{ matrix.shellfiles }}
        run: shellcheck -e SC1090 -e SC1091 -e SC2148 ${{ matrix.shellfiles }}
