name: lint

on:
  push:
    branches: [ master ]
    paths:
      - install.sh
      - .github/workflows/lint.yml
  workflow_dispatch:

jobs:
  lint_install_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check install.sh
        run: shellcheck install.sh
  lint_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check bashrc
        run: shellcheck -e SC1091 -e SC2148 bash/bashrc
      - name: Check bash_profile
        run: shellcheck -e SC1090 -e SC2148 bash/bash_profile
      - name: Check bash_logout
        run: shellcheck -e SC1090 -e SC2148 bash/bash_logout
