name: lint

on:
  push:
    branches: [ master ]
    paths: [ install.sh ]

jobs:
  lint_install_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check install.sh
        run: shellcheck install.sh
  lint_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check bashrc
        run: shellcheck -e SC1091 SC2148 bash/bashrc
      - name: Check bash_profile
        run: shellcheck -e SC1090 SC2148 bash/bash_profile
      - name: Check bash_logout
        run: shellcheck -e SC1090 SC2148 bash/bash_logout
