name: install script test

on:
  push:
    branches: [ master ]

jobs:
  macos_test:
    runs-on: macos-latest
    steps:
      - name: Debug
        run: pwd
      - name: Debug
        run: ls -l
      - name: Debug
        run: ./install.sh minimum
      - name: Run install.sh minimum
        run: install.sh minimum
      - name: Run install.sh link
        run: install.sh link
      - name: Run install.sh git
        run: install.sh git
      - name: Run install.sh all
        run: install.sh all
