name: macos

on:
  push:
    branches: [ master ]
    paths:
      - install.sh
      - .github/workflows/macos.yml
  workflow_dispatch:

jobs:
  macos_test_backup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install.sh backup
        run: ./install.sh backup
  macos_test_minimum:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install.sh minimum
        run: ./install.sh minimum
      - name: Load .bash_profile
        run: |
          bash ~/.bash_profile 2> error.log; cat error.log
          if [ -s error.log ]; then false; fi
      - name: Load .bashrc
        run: |
          bash ~/.bashrc 2> error.log; cat error.log
          if [ -s error.log ]; then false; fi
  macos_test_link:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install.sh link
        run: ./install.sh link
