name: macos

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/macos.yml
      - install.sh
      - sh/*
      - zsh/*
  workflow_dispatch:

jobs:
  macos_test_backup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install.sh --minimum
        run: ./install.sh --minimum
      - name: Load .zshrc
        run: |
          zsh ~/.zshrc 2> error.log; cat error.log
          if [ -s error.log ]; then false; fi
  macos_test_minimum:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install.sh --minimum --backup
        run: ./install.sh --minimum --backup
      - name: Load .zshrc
        run: |
          zsh ~/.zshrc 2> error.log; cat error.log
          if [ -s error.log ]; then false; fi
  macos_test_link:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install.sh --minimum --force
        run: ./install.sh --minimum --backup
      - name: Load .zshrc
        run: |
          zsh ~/.zshrc 2> error.log; cat error.log
          if [ -s error.log ]; then false; fi
